name: Publish to Github Pages

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run flutter test and analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@vs


      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed
      - name: Analyze project source
        run: dart analyze

